
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Tables } from '@/types/database';

const SUPABASE_URL = "https://ivdiyobtekwhijresrvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZGl5b2J0ZWt3aGlqcmVzcnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTgyNDgsImV4cCI6MjA2MTkzNDI0OH0.8miIQcH7FqAmpJMbbniTDWyd-ebfSJJoskYNeRIUScY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type-safe helper functions
export const getProfiles = () => {
  return supabase.from('profiles');
};

export const getSeniorProfiles = () => {
  return supabase.from('senior_profiles');
};

export const getReports = () => {
  return supabase.from('reports');
};
